name: Node.js CICD
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Upload HTML artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build
      - name: Deploy to GitHub Pages
        id: deploypages
        uses: actions/deploy-pages@v2
